exclude: [ "less", "CNAME", "Makefile", "LICENSE", "_assets", "Gemfile", "Gemfile.lock", "rakefile" ]
environments:
 development:
  url: http://localhost:4000
 production:
  url: http://colaboratorio.colaborativa.eu